### ISSUE TITLE
Support Feature Policy

### ISSUE THREAD

**Issue by jelly** [GoogleCloudPlatform/flask-talisman#25]
The Feature-Policy is a relatively new header which is supported in Chrome which would be nice to have supported as well.

https://scotthelme.co.uk/a-new-security-header-feature-policy/

**Comment by theacodes** [comment]
Sounds cool, would you be willing to send a PR for it?

**Comment by jelly** [comment]
Sure, I've been writing up some code. I think it's the most logical to adapt the same format as CSP which would implicate refactoring the policy parsing code so that I don't have to copy paste the parsing code.

I've also just stumbled on this new feature, so testing/development some time :)
