### ISSUE TITLE
How about renaming the package to flask-talisman?

### ISSUE THREAD

**Issue by lipis** [GoogleCloudPlatform/flask-talisman#3]
For various reasons (conventions, OCD and more):

-------------------------------------

Not sure where I read it, but I think there is a convention for Flask extensions to name them with `flask` prefix.

For example one of my `requirements.txt` looks like this (which is pretty cool, because I know exactly which one has a dependency on Flask)

```
...
flask==0.11.1
flask-babel==0.11.1
flask-login==0.4.0
flask-oauthlib==0.9.3
flask-restful==0.3.5
flask-wtf==0.13.1
...
talisman==0.1.0
...
```

and directories look like this:

<img width="195" alt="screen shot 2016-12-02 at 21 09 06" src="https://cloud.githubusercontent.com/assets/125676/20848731/a2887734-b8d3-11e6-8d83-1eb2afd49bcd.png">

----------------------------

Even though there is no real conflict, there might be some confusion from the example in `README`.

<img width="572" alt="screen shot 2016-12-02 at 21 21 06" src="https://cloud.githubusercontent.com/assets/125676/20849115/6afb1054-b8d5-11e6-9262-3ec373b1ebf8.png">

----------------------------

Another reason is to avoid conflicts when importing modules instead of classes when we will have to import the `talisman` object to add extra rules to the endpoints. Because there is no better name to name this object, other than `talisman`.

If the coding convention is to `import module` (instead of `from module import something`) then the suggested example will have to be adjusted like this ([I agree with Martijn Pieters](http://softwareengineering.stackexchange.com/questions/187403/import-module-vs-from-module-import-function/187471)):

```python
from flask import Flask
import talisman as flask_talisman

app = Flask(__name__)
# Just to avoid having a different name of that variable for alter usages.
talisman = flask_talisman.Talisman(app) 

@app.route('/normal')
def normal():
    return 'Normal'

@app.route('/embeddable')
@talisman(frame_options=ALLOW_FROM, frame_options_allow_from='*')
def embeddable():
    return 'Embeddable'
```

---------------------------------

I understand that this will break a bunch of things, but in a long run this will be better, plus the actual name of this repo is already `flask-talisman`, so we should be able to install it like the rest of the Flask extensions: `pip install flask-talisman`.

**Comment by lipis** [comment]
With this change we could also release the version `1.0.0`.

**Comment by jonparrott** [comment]
I'm cool with it. Do you want to send the PR to do it? I can handle the PyPI registration.

**Comment by lipis** [comment]
I can try :)

**Comment by jonparrott** [comment]
Awesome. :)
