### ISSUE TITLE
add possibility to disable header x-content-security-policy since it is deprecated

### ISSUE THREAD

**Issue by Heisendev** [GoogleCloudPlatform/flask-talisman#38]
the header `x-content-security-policy` is deprecated and it is know to have unexpected behavior when having both `content-security-policy` and `x-content-security-policy`

source : https://content-security-policy.com/

**Comment by theacodes** [comment]
Very cool. This should be an easy change to make, are you interested in submitting a pull request, @Heisendev?

**Comment by Heisendev** [comment]
yes it's coming in a few minutes

**Comment by Heisendev** [comment]
and it is open ! :)

**Comment by theacodes** [comment]
You're awesome. :)

*From: *Michael Hermet <notifications@github.com>
*Date: *Wed, May 15, 2019 at 8:51 AM
*To: *GoogleCloudPlatform/flask-talisman
*Cc: *Thea Flowers, Comment

yes it's coming in a few minutes
