### ISSUE TITLE
unsafe-inline error from 3rd party srcs

### ISSUE THREAD

**Issue by rbcabreraUPM** [GoogleCloudPlatform/flask-talisman#49]
I am getting this error 
_Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution._

for 

1. https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js
2. https://www.paypal.com/sdk/js?client-id={{paypalKey}}&currency={{gatewaypricing['PAYPAL']['currency']}}&disable-funding=credit,card

**Comment by theacodes** [comment]
Hi there! This question is probably better suited for Stackoverflow. We're happy to help with getting your headers showing up, but debugging a specific content security policy is a bit out of our wheelhouse.

Good luck!

**Comment by rbcabreraUPM** [comment]
> Hi there! This question is probably better suited for Stackoverflow. We're happy to help with getting your headers showing up, but debugging a specific content security policy is a bit out of our wheelhouse.
> 
> Good luck!

Problem is fixed for sweetalert. I was actually missing out the quotation marks thats why chrome was counting the hash as an invalid source.

anyway, thank you
