### ISSUE TITLE
preload should not be a default setting

### ISSUE THREAD

**Issue by estein-de** [GoogleCloudPlatform/flask-talisman#5]
From README: 

"Enables HSTS preloading. If you register your application with Google's HSTS preload list, Firefox and Chrome will never load your site over a non-secure connection."

See hstspreload.org opt in note - https://hstspreload.org/#opt-in - please remove preload from the default settings and expose it as a flag you can set.

**Comment by jonparrott** [comment]
@estein-de thanks for reporting, this is fixed in 0.2.1.

**Comment by estein-de** [comment]
Please re-open this issue to update the documentation/readme?

**Comment by jonparrott** [comment]
@estein-de nice catch, fixed by 7677441fb4
