### ISSUE TITLE
Nonce length is incorrect

### ISSUE THREAD

**Issue by bazzadp** [GoogleCloudPlatform/flask-talisman#55]
flask-talisman uses the following code to generate a random nonce (as added in #17 and #18):

```py
NONCE_LENGTH = 16
...
            flask.request.csp_nonce = get_random_string(NONCE_LENGTH)
...
try:
    import secrets
    get_random_string = secrets.token_urlsafe  # pragma: no cover

except ImportError:  # pragma: no cover
    import random
    import string
    rnd = random.SystemRandom()

    def get_random_string(length):
        allowed_chars = (
            string.ascii_lowercase +
            string.ascii_uppercase +
            string.digits)
        return ''.join(
            rnd.choice(allowed_chars)
            for _ in range(length))
```

That is it sets the `NONCE_LENGTH` to 16, then it tries to generate the NONCE (of length 16) using `secrets.token_urlsafe` and falls back to it's own random generator if that library is not available.

The problem is that [`secrets.token_urlsafe` does not generate a value of that length](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe):

> Return a random URL-safe text string, containing nbytes random bytes. The text is Base64 encoded, so on average each byte results in approximately 1.3 characters.

This means we typically get a nonce of length 22 instead of one of length 16 that we asked for.

If you just use the manually defined function you do get a nonce of length 16 each time.

I always wondered by the [nu validator](https://validator.w3.org/nu/) complained about this, and finally got round to investigating:

> **Warning:** Content-Security-Policy HTTP header: Bad content security policy: Invalid base64-value (should be multiple of 4 bytes: 22).

Other than that it doesn't seem to cause a problem. [This StackOverflow answer seems to give a reason why](https://stackoverflow.com/a/26632221/2144578), but not sure it really affects CSPs, but still... it's technically an incorrect base64 number so think we should at least consider fixing.

Do you need to use `secrets.token_urlsafe` given you are restricting the allowed characters to URL safe characters anyway?

I see this was added in #28 by as part of performance improvements but not sure if the overhead was that significant or if it is preferable to generate a valid base64 and take the slight performance hit? Especially given the other performance improvement in that pull request (which was to make the `SystemRandom` call once, rather than once per character) will have greatly reduced the performance anyway.

The alternative is to switch `secrets.token_urlsafe` with `secrets.token_hex` which will generate a 32-length nonce but with a reduced character set (0-9a-f) for an input of 16. Is the doubling in the length sufficient to make up from the greatly reduced character set? I'd guess not as going from 62-ish characters to just 16.

So I'd suggest removing the `secrets.token_urlsafe`call and instead using the fallback function.

@nealedj tagging you in this for any comments as the added the original code, and the performance improvement.

**Comment by theacodes** [comment]
Sounds good. Are you up for sending a PR?

**Comment by bazzadp** [comment]
> Sounds good. Are you up for sending a PR?

Sure. Will do that now.

I'm actually thinking to continue to use `secrets.token_urlsafe` ([since it's more cryptographically secure than `random`](https://docs.python.org/3/library/secrets.html)) but instead limit the returned length:

```
try:
    import secrets
    def get_random_string(length):
        return secrets.token_urlsafe(length)[:length] # pragma: no cover
```
