### ISSUE TITLE
no-referrer ineffective

### ISSUE THREAD

**Issue by mrx23dot** [GoogleCloudPlatform/flask-talisman#72]
```
csp = {
  'referrer_policy': 'no-referrer',
}
Talisman(app, content_security_policy=csp)
```
still gives

still gives:
`Referrer-Policy: strict-origin-when-cross-origin`
in browser.

flask-talisman==0.7.0

**Comment by tunetheweb** [comment]
`referrer_policy` is not `part of content-security_policy`. You just want the following:

```python
Talisman(app, referrer_policy='no-referrer')
```

**Comment by mrx23dot** [comment]
thank you!
